In [1]:
# Cross Validation Implementation

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df = df[['survived','pclass','sex','age','sibsp','parch','fare','embarked','alone']]

In [12]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [5]:
def func(value):
    if value == 'male':
        return 1
    else:
        return 0
df['sex'] = df['sex'].map(func)

In [11]:
df['embarked'].value_counts()

embarked
2    644
0    168
1     79
Name: count, dtype: int64

In [10]:
def func1(value):
    if value == 'S':
        return 2
    elif value == 'C':
        return 0
    else:
        return 1
df['embarked'] = df['embarked'].map(func1)

In [16]:
mean = df['age'].mean()

In [19]:
df['age'] = df['age'].fillna(mean)

In [20]:
df['age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [21]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
alone       0
dtype: int64

In [22]:
final_df = df.astype(int)

In [24]:
final_df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[891 rows x 9 columns]

In [25]:
X = df.drop('survived', axis=1)
y = df['survived']

In [26]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [27]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [28]:
X_scaled

array([[ 0.82737724,  0.73769513, -0.5924806 , ..., -0.50244517,
         0.58871704, -1.2316449 ],
       [-1.56610693, -1.35557354,  0.63878901, ...,  0.78684529,
        -1.93921974, -1.2316449 ],
       [ 0.82737724, -1.35557354, -0.2846632 , ..., -0.48885426,
         0.58871704,  0.81192233],
       ...,
       [ 0.82737724, -1.35557354,  0.        , ..., -0.17626324,
         0.58871704, -1.2316449 ],
       [-1.56610693,  0.73769513, -0.2846632 , ..., -0.04438104,
        -1.93921974,  0.81192233],
       [ 0.82737724,  0.73769513,  0.17706291, ..., -0.49237783,
        -0.67525135,  0.81192233]], shape=(891, 8))

In [29]:
model = SVC(kernel='linear')

In [30]:
scores = cross_val_score(model, X_scaled, y, cv=5, scoring='accuracy')

In [31]:
scores

array([0.79888268, 0.80898876, 0.78651685, 0.75280899, 0.78651685])

In [32]:
print(scores.mean())

0.7867428284476806